"""GitHub code-search query catalog for mnemonic exposure hunting.

Two complementary strategies:

1. **Code constructs** — API / env / library patterns that almost always sit
   next to a real seed in application code (higher precision).

2. **BIP39 word n-grams** — short phrases of uncommon wordlist words, often
   only appear when someone pasted a full mnemonic (higher recall, more noise).

GitHub code search is rate-limited; keep the default catalog focused.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache


@dataclass(frozen=True, slots=True)
class SearchQuery:
    """One GitHub code-search query with provenance metadata."""

    query: str
    category: str  # code | env | bip39_ngram | keyword
    note: str = ""


# ---------------------------------------------------------------------------
# 1) Code / library constructs (SDK & app patterns)
# ---------------------------------------------------------------------------
CODE_CONSTRUCT_QUERIES: tuple[SearchQuery, ...] = (
    SearchQuery(
        'fromMnemonic(',
        "code",
        "ethers/web3 Wallet.fromMnemonic",
    ),
    SearchQuery(
        "from_mnemonic(",
        "code",
        "python/rust from_mnemonic",
    ),
    SearchQuery(
        "generateMnemonic",
        "code",
        "bip39 generateMnemonic / ethers",
    ),
    SearchQuery(
        "mnemonicToSeed",
        "code",
        "bip39.mnemonicToSeed*",
    ),
    SearchQuery(
        "validateMnemonic(",
        "code",
        "bip39.validateMnemonic",
    ),
    SearchQuery(
        "HDNode.fromMnemonic",
        "code",
        "ethers HDNode",
    ),
    SearchQuery(
        "Wallet.fromPhrase",
        "code",
        "ethers v6 Wallet.fromPhrase",
    ),
    SearchQuery(
        "Mnemonic.from_phrase",
        "code",
        "solders/solana Mnemonic.from_phrase",
    ),
    SearchQuery(
        "Bip39SeedGenerator",
        "code",
        "bip_utils seed generator",
    ),
    SearchQuery(
        "bip39.mnemonic",
        "code",
        "node bip39 package",
    ),
    SearchQuery(
        "seedPhrase =",
        "code",
        "JS/TS seedPhrase assignment",
    ),
    SearchQuery(
        "recoveryPhrase =",
        "code",
        "recoveryPhrase assignment",
    ),
    SearchQuery(
        "secretRecoveryPhrase",
        "code",
        "MetaMask-style secretRecoveryPhrase",
    ),
    SearchQuery(
        "mnemonic:" ,
        "code",
        "YAML/JSON mnemonic field",
    ),
    SearchQuery(
        '"mnemonic":',
        "code",
        "JSON mnemonic key",
    ),
    SearchQuery(
        "process.env.MNEMONIC",
        "code",
        "Node env MNEMONIC",
    ),
    SearchQuery(
        "os.environ[\"MNEMONIC\"]",
        "code",
        "Python env MNEMONIC",
    ),
    SearchQuery(
        "os.Getenv(\"MNEMONIC\")",
        "code",
        "Go env MNEMONIC",
    ),
)

# ---------------------------------------------------------------------------
# 2) Env / file oriented
# ---------------------------------------------------------------------------
ENV_QUERIES: tuple[SearchQuery, ...] = (
    SearchQuery("MNEMONIC= filename:.env", "env", ".env MNEMONIC="),
    SearchQuery("SEED_PHRASE= filename:.env", "env", ".env SEED_PHRASE="),
    SearchQuery("WALLET_MNEMONIC= filename:.env", "env", ".env WALLET_MNEMONIC="),
    SearchQuery("SECRET_MNEMONIC= OR RECOVERY_PHRASE=", "env", "env secret names"),
    SearchQuery(
        "filename:wallet.txt OR filename:seed.txt OR filename:mnemonic.txt",
        "env",
        "common dump filenames",
    ),
    SearchQuery(
        "filename:secrets.json mnemonic OR seed",
        "env",
        "secrets.json",
    ),
    SearchQuery(
        "filename:.env.local MNEMONIC OR SEED",
        "env",
        ".env.local",
    ),
)

# ---------------------------------------------------------------------------
# 3) Keyword / prose (docs + accidental pastes)
# ---------------------------------------------------------------------------
KEYWORD_QUERIES: tuple[SearchQuery, ...] = (
    SearchQuery(
        '"seed phrase" wallet -test -example -demo -hardhat',
        "keyword",
        "prose seed phrase",
    ),
    SearchQuery(
        '"recovery phrase" wallet -test -hardhat -example',
        "keyword",
        "prose recovery phrase",
    ),
    SearchQuery(
        '"secret recovery phrase" -test -metamask/extension',
        "keyword",
        "MetaMask recovery wording",
    ),
    # Avoid parentheses / complex boolean — GitHub code search often returns 422
    SearchQuery(
        '"12 words" mnemonic seed wallet -test',
        "keyword",
        "12-word mention",
    ),
    SearchQuery(
        '"24 words" mnemonic seed -test -example',
        "keyword",
        "24-word mention",
    ),
)


# Mid/low-frequency BIP39 English words (avoid ultra-common like "the" — not in list).
# Prefer words that rarely appear outside wallet dumps / wordlist copies.
# We build 3- and 4-grams as quoted phrases + wallet context to cut FP.
_BIP39_SEED_WORDS_FOR_NGRAMS: tuple[str, ...] = (
    # scattered mid-list / less everyday English in code comments
    "zoo",
    "zebra",
    "zigzag",
    "wrist",
    "wreck",
    "wrench",
    "village",
    "violin",
    "virus",
    "volume",
    "voyage",
    "walnut",
    "warrior",
    "weasel",
    "whisper",
    "whisper",
    "ribbon",
    "rhythm",
    "saddle",
    "satoshi",
    "scheme",
    "scissors",
    "scorpion",
    "seat",
    "setup",
    "shadow",
    "shaft",
    "shallow",
    "share",
    "shed",
    "shell",
    "sheriff",
    "shield",
    "shift",
    "shine",
    "ship",
    "shiver",
    "shock",
    "shoe",
    "shoot",
    "shop",
    "short",
    "shoulder",
    "shove",
    "shrimp",
    "shrug",
    "shuffle",
    "shy",
    "sibling",
    "sick",
    "side",
    "siege",
    "sight",
    "sign",
    "silent",
    "silk",
    "silly",
    "silver",
    "similar",
    "simple",
    "since",
    "sing",
    "siren",
    "sister",
    "situate",
    "six",
    "size",
    "skate",
    "sketch",
    "ski",
    "skill",
    "skin",
    "skirt",
    "skull",
    "slab",
    "slam",
    "sleep",
    "slender",
    "slice",
    "slide",
    "slight",
    "slim",
    "slogan",
    "slot",
    "slow",
    "slush",
    "small",
    "smart",
    "smile",
    "smoke",
    "smooth",
    "snack",
    "snake",
    "snap",
    "sniff",
    "snow",
    "soap",
    "soccer",
    "social",
    "sock",
    "soda",
    "soft",
    "solar",
    "soldier",
    "solid",
    "solution",
    "solve",
    "someone",
    "song",
    "soon",
    "sorry",
    "sort",
    "soul",
    "sound",
    "soup",
    "source",
    "south",
    "space",
    "spare",
    "spatial",
    "spawn",
    "speak",
    "special",
    "speed",
    "spell",
    "spend",
    "sphere",
    "spice",
    "spider",
    "spike",
    "spin",
    "spirit",
    "split",
    "spoil",
    "sponsor",
    "spoon",
    "sport",
    "spot",
    "spray",
    "spread",
    "spring",
    "spy",
    "square",
    "squeeze",
    "squirrel",
    "stable",
    "stadium",
    "staff",
    "stage",
    "stairs",
    "stamp",
    "stand",
    "start",
    "state",
    "stay",
    "steak",
    "steel",
    "stem",
    "step",
    "stereo",
    "stick",
    "still",
    "sting",
    "stock",
    "stomach",
    "stone",
    "stool",
    "story",
    "stove",
    "strategy",
    "street",
    "strike",
    "strong",
    "struggle",
    "student",
    "stuff",
    "stumble",
    "style",
    "subject",
    "submit",
    "subway",
    "success",
    "such",
    "sudden",
    "suffer",
    "sugar",
    "suggest",
    "suit",
    "summer",
    "sun",
    "sunny",
    "sunset",
    "super",
    "supply",
    "supreme",
    "sure",
    "surface",
    "surge",
    "surprise",
    "surround",
    "survey",
    "suspect",
    "sustain",
    "swallow",
    "swamp",
    "swap",
    "swarm",
    "swear",
    "sweet",
    "swift",
    "swim",
    "swing",
    "switch",
    "sword",
    "symbol",
    "symptom",
    "syrup",
    "system",
    "table",
    "tackle",
    "tag",
    "tail",
    "talent",
    "talk",
    "tank",
    "tape",
    "target",
    "task",
    "taste",
    "tattoo",
    "taxi",
    "teach",
    "team",
    "tell",
    "ten",
    "tenant",
    "tennis",
    "tent",
    "term",
    "test",
    "text",
    "thank",
    "that",
    "theme",
    "then",
    "theory",
    "there",
    "they",
    "thing",
    "this",
    "thought",
    "three",
    "thrive",
    "throw",
    "thumb",
    "thunder",
    "ticket",
    "tide",
    "tiger",
    "tilt",
    "timber",
    "time",
    "tiny",
    "tip",
    "tired",
    "tissue",
    "title",
    "toast",
    "tobacco",
    "today",
    "toddler",
    "toe",
    "together",
    "toilet",
    "token",
    "tomato",
    "tomorrow",
    "tone",
    "tongue",
    "tonight",
    "tool",
    "tooth",
    "top",
    "topic",
    "topple",
    "torch",
    "tornado",
    "tortoise",
    "toss",
    "total",
    "tourist",
    "toward",
    "tower",
    "town",
    "toy",
    "track",
    "trade",
    "traffic",
    "tragic",
    "train",
    "transfer",
    "trap",
    "trash",
    "travel",
    "tray",
    "treat",
    "tree",
    "trend",
    "trial",
    "tribe",
    "trick",
    "trigger",
    "trim",
    "trip",
    "trophy",
    "trouble",
    "truck",
    "true",
    "truly",
    "trumpet",
    "trust",
    "truth",
    "try",
    "tube",
    "tuition",
    "tumble",
    "tuna",
    "tunnel",
    "turkey",
    "turn",
    "turtle",
    "twelve",
    "twenty",
    "twice",
    "twin",
    "twist",
    "two",
    "type",
    "typical",
    "ugly",
    "umbrella",
    "unable",
    "unaware",
    "uncle",
    "uncover",
    "under",
    "undo",
    "unfair",
    "unfold",
    "unhappy",
    "unhealthy",
    "uniform",
    "unique",
    "unit",
    "universe",
    "unknown",
    "unlock",
    "until",
    "unusual",
    "unveil",
    "update",
    "upgrade",
    "uphold",
    "upon",
    "upper",
    "upset",
    "urban",
    "urge",
    "usage",
    "use",
    "used",
    "useful",
    "useless",
    "usual",
    "utility",
    "vacant",
    "vacuum",
    "vague",
    "valid",
    "valley",
    "valve",
    "van",
    "vanish",
    "vapor",
    "various",
    "vast",
    "vault",
    "vehicle",
    "velvet",
    "vendor",
    "venture",
    "venue",
    "verb",
    "verify",
    "version",
    "very",
    "vessel",
    "veteran",
    "viable",
    "vibrant",
    "vicious",
    "victory",
    "video",
    "view",
    "view",
    "village",
    "vintage",
    "violin",
    "virtual",
    "virus",
    "visa",
    "visit",
    "visual",
    "vital",
    "vivid",
    "vocal",
    "voice",
    "void",
    "volcano",
    "volume",
    "vote",
    "voyage",
    "wage",
    "wagon",
    "wait",
    "walk",
    "wall",
    "walnut",
    "want",
    "warfare",
    "warm",
    "warrior",
    "wash",
    "wasp",
    "waste",
    "water",
    "wave",
    "way",
    "wealth",
    "weapon",
    "wear",
    "weasel",
    "weather",
    "web",
    "wedding",
    "weekend",
    "weird",
    "welcome",
    "west",
    "wet",
    "whale",
    "what",
    "wheat",
    "wheel",
    "when",
    "where",
    "whip",
    "whisper",
    "wide",
    "width",
    "wife",
    "wild",
    "will",
    "win",
    "window",
    "wine",
    "wing",
    "wink",
    "winner",
    "winter",
    "wire",
    "wisdom",
    "wise",
    "wish",
    "witness",
    "wolf",
    "woman",
    "wonder",
    "wood",
    "wool",
    "word",
    "work",
    "world",
    "worry",
    "worth",
    "wrap",
    "wreck",
    "wrestle",
    "wrist",
    "write",
    "wrong",
    "yard",
    "year",
    "yellow",
    "you",
    "young",
    "youth",
    "zebra",
    "zero",
    "zone",
    "zoo",
)


def _unique_preserve(seq: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for x in seq:
        if x not in seen:
            seen.add(x)
            out.append(x)
    return out


@lru_cache(maxsize=1)
def _ngram_source_words() -> tuple[str, ...]:
    """Prefer actual BIP39 english list when available; fall back to curated."""
    try:
        from seedleak.detector.bip39 import load_wordlist

        words, _ = load_wordlist("english")
        # Prefer less common tail of the alphabetized list + distinctive tokens
        # (still valid BIP39 words only).
        distinctive = [
            w
            for w in words
            if w
            in {
                "satoshi",
                "zoo",
                "zebra",
                "zigzag",
                "avalanche",
                "atom",
                "galaxy",
                "quantum",
                "phoenix",
                "orbit",
                "neon",
                "magma",
                "lava",
                "fossil",
                "fossil",
                "diesel",
                "cricket",
                "coconut",
                "cactus",
                "bamboo",
                "banana",
                "buffalo",
                "butterfly",
                "canyon",
                "cascade",
                "celery",
                "cereal",
                "chimney",
                "cigar",
                "cinnamon",
                "clay",
                "cliff",
                "clinic",
                "clog",
                "cloth",
                "cloud",
                "clown",
                "club",
                "clump",
                "cluster",
                "clutch",
                "coach",
                "coast",
                "coconut",
                "code",
                "coffee",
                "coil",
                "coin",
                "collect",
                "color",
                "column",
                "combine",
                "come",
                "comfort",
                "comic",
                "common",
                "company",
                "concert",
                "conduct",
                "confirm",
                "congress",
                "connect",
                "consider",
                "control",
                "convince",
                "cook",
                "cool",
                "copper",
                "copy",
                "coral",
                "core",
                "corn",
                "correct",
                "cost",
                "cotton",
                "couch",
                "country",
                "couple",
                "course",
                "cousin",
                "cover",
                "coyote",
                "crack",
                "cradle",
                "craft",
                "cram",
                "crane",
                "crash",
                "crater",
                "crawl",
                "crazy",
                "cream",
                "credit",
                "creek",
                "crew",
                "cricket",
                "crime",
                "crisp",
                "critic",
                "crop",
                "cross",
                "crouch",
                "crowd",
                "crucial",
                "cruel",
                "cruise",
                "crumble",
                "crunch",
                "crush",
                "cry",
                "crystal",
                "cube",
                "culture",
                "cup",
                "cupboard",
                "curious",
                "current",
                "curtain",
                "curve",
                "cushion",
                "custom",
                "cute",
                "cycle",
            }
            or w.startswith(("z", "y", "x", "w", "v", "u", "q"))
        ]
        # Keep order stable and cap
        distinctive = _unique_preserve(distinctive)
        if len(distinctive) < 80:
            # mix with every Nth word from full list for coverage
            distinctive.extend(words[::25])
        return tuple(_unique_preserve(distinctive)[:200])
    except Exception:
        return tuple(_unique_preserve(list(_BIP39_SEED_WORDS_FOR_NGRAMS)))


def build_bip39_ngram_queries(
    *,
    n: int = 3,
    count: int = 40,
    stride: int = 3,
) -> list[SearchQuery]:
    """Build quoted n-gram queries from BIP39 words + wallet context.

    Example: ``"satoshi scale scene" (mnemonic OR seed OR wallet)``

    These are **not** full mnemonics — just bait phrases that often sit
    inside a pasted 12/24-word string. Exclude pure wordlist files via -path.
    """
    words = list(_ngram_source_words())
    if len(words) < n:
        return []
    out: list[SearchQuery] = []
    i = 0
    while len(out) < count and i + n <= len(words):
        gram = " ".join(words[i : i + n])
        # Require wallet-ish context; drop obvious wordlist paths when possible
        # Keep query simple for GitHub code search (no paren groups → fewer 422s)
        q = f'"{gram}" mnemonic OR seed OR wallet OR bip39'
        out.append(
            SearchQuery(
                q,
                "bip39_ngram",
                f"{n}-gram from BIP39 wordlist offset={i}",
            )
        )
        i += stride
    return out


def default_hunt_queries(
    *,
    include_code: bool = True,
    include_env: bool = True,
    include_keyword: bool = True,
    include_ngrams: bool = True,
    ngram_count: int = 40,
    ngram_n: int = 3,
) -> list[SearchQuery]:
    """Full default catalog for a max-power hunt."""
    qs: list[SearchQuery] = []
    if include_code:
        qs.extend(CODE_CONSTRUCT_QUERIES)
    if include_env:
        qs.extend(ENV_QUERIES)
    if include_keyword:
        qs.extend(KEYWORD_QUERIES)
    if include_ngrams:
        qs.extend(
            build_bip39_ngram_queries(n=ngram_n, count=ngram_count)
            + build_bip39_ngram_queries(n=4, count=max(10, ngram_count // 2), stride=5)
        )
    # Dedupe by query string
    seen: set[str] = set()
    uniq: list[SearchQuery] = []
    for q in qs:
        if q.query in seen:
            continue
        seen.add(q.query)
        uniq.append(q)
    return uniq


def queries_as_strings(items: list[SearchQuery] | None = None) -> list[str]:
    items = items or default_hunt_queries()
    return [q.query for q in items]
